"""Add email address in Account Table for sending mailers.

Revision ID: 8cf43589ca8b
Revises: 3828e380de20
Create Date: 2018-08-28 12:47:31.858127

"""

# revision identifiers, used by Alembic.
revision = '8cf43589ca8b'
down_revision = '3828e380de20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('email_address', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'email_address')
    # ### end Alembic commands ###